spring:
  main:
    web-application-type: REACTIVE
  application:
    name: gateway-service
  cloud:
   gateway:
     default-filters:
        - StripPrefix=1
        - AddRequestHeader=proxied, true
     routes:
     - id: admin-service
       uri: http://admin-service:9000
       predicates:
         - Path=/admin/**
     - id: student-service
       uri: http://student-service:9001
       predicates:
         - Path=/student/**
     - id: teacher-service
       uri: http://teacher-service:9002
       predicates:
         - Path=/teacher/**
     - id: user-service
       uri: http://user-service:9003
       predicates:
         - Path=/user/**
     

server:
    port: 8080

#logging:
#  level:
#    root: INFO
##    '[org.springframework]' : INFO
#    '[org.springframework.cloud]' : INFO
#    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    
