spring:
#  sql:
#    init:
#      mode: always
  application:
    name: admin-service
  datasource:
    username: max
    password: pas
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
#    defer-datasource-initialization: true
#    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none

server:
    port: 9000

logging:
  level:
    '[org.springframework]' : INFO
    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://admin-db:5432/ems
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    


