spring:
  application:
    name: admin-service_test
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  cloud:
      discovery:
        enabled: false

  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


  spring.autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration