spring:
  kafka:
    bootstrap-servers: "192.168.201.201:32002"
    topic: laboratory
  main:
    web-application-type: NONE
  application:
    name: kafka-consumer
  cloud:
server:
  port: 9002

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

#logging:
#  level:
#    root: INFO
##    '[org.springframework]' : INFO
#    '[org.springframework.cloud]' : INFO
#    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    
