spring:
  kafka:
    bootstrap-servers: "192.168.201.201:29092"
    topic: laboratory
  main:
    web-application-type: NONE
  application:
    name: kafka-producer
  cloud:
server:
    port: 9001

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    
